environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
#

build_script:
  - gradlew isCI displayCommitHash buildPlugin --info
  - gradlew verifyPlugin --info
  - move C:\Users\appveyor\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\LATEST-EAP-SNAPSHOT\ddf5b2bb091da6a974316b36d75db2732a40c1b9\ideaIC-LATEST-EAP-SNAPSHOT\bin\*.log .
#

cache:
  - C:\Users\appveyor\.gradle

artifacts:
  - path: 'build\distributions\*.zip'
    name: intellij-dtlc
  - path: '*.log'
    name: java-core-dump
#
